### ISSUE TITLE
DevKit Package versions for Jan-2017 unavailable, can't build

### ISSUE THREAD

**Issue by garoyeri** [pds-technology/witsml#1]
I can't build the solution since the 20170112 versions of the DevKits-PDS packages are not on nuget.org.  I noticed the regular Energistics ones "EnergisticsDevKit" https://www.nuget.org/packages/EnergisticsDevKit/ is there and looks to be the Jan-2017 version.

**Comment by bmdiaz** [comment]
Hi Garo, thank you for pointing out the oversight.  I have just uploaded the latest versions of the packages and they should be available shortly.

Regards,
Bobby

**Comment by garoyeri** [comment]
I see them, Thanks!
