### ISSUE TITLE
STORE sln is missing - impossible to build the WitsML server

### ISSUE THREAD

**Issue by tuurke63** [pds-technology/witsml#11]
Hello all,

in the merge of march 26, the files "PDS.WITSMLstudio.Store.sln" and "PDS.WITSMLstudio.Store.sln.DotSettings" were deleted.  As a consequence it's not possible to build the WitsML server.

**Comment by EricGriffith** [comment]
@tuurke63 Store is included in PDS.WITSMLstudio.sln.  You can build it by building that solution.
